#!/bin/bash

set -e  # exit immediately on error

export DOT="\033[32m ● \033[0m"
export CHECK="\033[32m ✔ \033[0m"
export LINECLEAR="\033[1G\033[2K" # position to column 1; erase whole line
export ERROR="\033[31m ❌ ERROR \033[0m"
export RESET="\033[0m"

exit_code=1
all_ts_files=$(git diff --cached --diff-filter=d --name-only | grep .ts$)
npx eslint $all_ts_files --quiet --fix
exit_code=$?

# Add to the commit list any filed updated by the linter
git add -f $all_ts_files

if [ $exit_code -ne 0 ]
then
  echo "${ERROR} eslint failed${RESET}"
  exit 1
else
  echo "${CHECK} eslint passed${RESET}"
  exit 0
fi


exit_code=1
all_other_files=$(git diff --cached --diff-filter=d --name-only | grep -E '(.css|.json|.less|.md)$')
npx prettier $all_other_files --write
exit_code=$?

# Add to the commit list any filed updated by prettier
git add -f $all_other_files

if [ $exit_code -ne 0 ]
then
  echo "${ERROR} prettier failed${RESET}"
  exit 1
else
  echo "${CHECK} prettier passed${RESET}"
  exit 0
fi


exit_code=1
npm run test
exit_code=$?

if [ $exit_code -ne 0 ]
then
  echo "${ERROR} Unit testing failed${RESET}"
  exit 1
else
  echo "${CHECK} Unit testing passed${RESET}"
  exit 0
fi

