const tseslint = require('@typescript-eslint/eslint-plugin');
const tsparser = require('@typescript-eslint/parser');
const prettier = require('eslint-plugin-prettier');
const prettierConfig = require('eslint-config-prettier');

module.exports = [
  {
    ignores: ['dist/**', 'node_modules/**', 'coverage/**', '*.min.js', '*.min.mjs'],
  },
  {
    files: ['**/*.ts', '**/*.js', '**/*.mjs'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        project: './tsconfig.eslint.json',
        ecmaVersion: 2020,
        extraFileExtensions: ['.less'],
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        globalThis: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        HTMLCollection: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        getComputedStyle: 'readonly',
        // Node.js globals
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        Buffer: 'readonly',
        // Jest globals
        describe: 'readonly',
        test: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      prettier: prettier,
    },
    rules: {
      ...prettierConfig.rules,
      '@typescript-eslint/triple-slash-reference': 'off',
      'no-restricted-globals': [
        'error',
        'postMessage',
        'blur',
        'focus',
        'close',
        'frames',
        'self',
        'parent',
        'opener',
        'top',
        'length',
        'closed',
        'location',
        'origin',
        'name',
        'locationbar',
        'menubar',
        'personalbar',
        'scrollbars',
        'statusbar',
        'toolbar',
        'status',
        'frameElement',
        'customElements',
        'external',
        'screen',
        'innerWidth',
        'innerHeight',
        'scrollX',
        'pageXOffset',
        'scrollY',
        'pageYOffset',
        'screenX',
        'screenY',
        'outerWidth',
        'outerHeight',
        'devicePixelRatio',
        'clientInformation',
        'screenLeft',
        'screenTop',
        'defaultStatus',
        'defaultstatus',
        'styleMedia',
        'onanimationend',
        'onanimationiteration',
        'onanimationstart',
        'onsearch',
        'ontransitionend',
        'onwebkitanimationend',
        'onwebkitanimationiteration',
        'onwebkitanimationstart',
        'onwebkittransitionend',
        'isSecureContext',
        'onabort',
        'onblur',
        'oncancel',
        'oncanplay',
        'oncanplaythrough',
        'onchange',
        'onclick',
        'onclose',
        'oncontextmenu',
        'oncuechange',
        'ondblclick',
        'ondrag',
        'ondragend',
        'ondragenter',
        'ondragleave',
        'ondragover',
        'ondragstart',
        'ondrop',
        'ondurationchange',
        'onemptied',
        'onended',
        'onerror',
        'onfocus',
        'oninput',
        'oninvalid',
        'onkeydown',
        'onkeypress',
        'onkeyup',
        'onload',
        'onloadeddata',
        'onloadedmetadata',
        'onloadstart',
        'onmousedown',
        'onmouseenter',
        'onmouseleave',
        'onmousemove',
        'onmouseout',
        'onmouseover',
        'onmouseup',
        'onmousewheel',
        'onpause',
        'onplay',
        'onplaying',
        'onprogress',
        'onratechange',
        'onreset',
        'onresize',
        'onscroll',
        'onseeked',
        'onseeking',
        'onselect',
        'onstalled',
        'onsubmit',
        'onsuspend',
        'ontimeupdate',
        'ontoggle',
        'onvolumechange',
        'onwaiting',
        'onwheel',
        'onauxclick',
        'ongotpointercapture',
        'onlostpointercapture',
        'onpointerdown',
        'onpointermove',
        'onpointerup',
        'onpointercancel',
        'onpointerover',
        'onpointerout',
        'onpointerenter',
        'onpointerleave',
        'onafterprint',
        'onbeforeprint',
        'onbeforeunload',
        'onhashchange',
        'onlanguagechange',
        'onmessage',
        'onmessageerror',
        'onoffline',
        'ononline',
        'onpagehide',
        'onpageshow',
        'onpopstate',
        'onrejectionhandled',
        'onstorage',
        'onunhandledrejection',
        'onunload',
        'performance',
        'stop',
        'open',
        'print',
        'captureEvents',
        'releaseEvents',
        'matchMedia',
        'moveTo',
        'moveBy',
        'resizeTo',
        'resizeBy',
        'getSelection',
        'find',
        'createImageBitmap',
        'scroll',
        'scrollTo',
        'scrollBy',
        'onappinstalled',
        'onbeforeinstallprompt',
        'crypto',
        'ondevicemotion',
        'ondeviceorientation',
        'ondeviceorientationabsolute',
        'indexedDB',
        'webkitStorageInfo',
        'chrome',
        'visualViewport',
        'speechSynthesis',
        'webkitRequestFileSystem',
        'webkitResolveLocalFileSystemURL',
        'openDatabase',
      ],
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      'no-unused-expressions': 'off',
      'prettier/prettier': [
        'error',
        {
          endOfLine: 'auto',
        },
      ],
      indent: 'off',
      'no-const-assign': 'warn',
      'no-this-before-super': 'warn',
      'no-unreachable': 'warn',
      'no-unused-vars': 'off',
      'constructor-super': 'warn',
      'block-scoped-var': 'error',
      'array-bracket-spacing': ['error', 'never'],
      'block-spacing': ['error', 'always'],
      'brace-style': 'off',
      'prefer-const': 'warn',
      'valid-typeof': 'error',
      'consistent-return': 'error',
      curly: ['warn', 'multi-or-nest'],
      eqeqeq: ['error', 'smart'],
      'guard-for-in': 'warn',
      'new-cap': 'warn',
      'no-bitwise': 'off',
      'no-console': 'off',
      'no-dupe-class-members': 'off',
      'no-else-return': 'warn',
      'no-eval': 'error',
      'no-fallthrough': 'error',
      'no-invalid-this': 'warn',
      'no-lone-blocks': 'warn',
      'no-return-assign': ['warn', 'always'],
      'no-redeclare': 'off',
      'no-self-compare': 'error',
      'no-sequences': 'warn',
      'no-unneeded-ternary': 'warn',
      'no-useless-call': 'warn',
      'no-var': 'error',
      'no-with': 'error',
      'no-delete-var': 'warn',
      'no-mixed-spaces-and-tabs': ['warn', 'smart-tabs'],
      'require-jsdoc': 'off',
      'space-infix-ops': ['error', { int32Hint: false }],
      'no-trailing-spaces': ['warn', { skipBlankLines: true }],
    },
  },
  {
    // TypeScript-specific rules
    files: ['**/*.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          args: 'after-used',
          ignoreRestSiblings: false,
        },
      ],
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-unused-expressions': 'warn',
      '@typescript-eslint/prefer-optional-chain': 'warn',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/naming-convention': [
        'warn',
        {
          selector: 'typeParameter',
          format: ['PascalCase'],
        },
      ],
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-use-before-define': [
        'error',
        {
          functions: false,
          classes: false,
          variables: false,
          typedefs: false,
        },
      ],
      '@typescript-eslint/no-this-alias': [
        'error',
        {
          allowedNames: ['self', 'that'],
        },
      ],
      '@typescript-eslint/no-for-in-array': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'warn',
      '@typescript-eslint/no-unnecessary-type-arguments': 'warn',
      '@typescript-eslint/array-type': ['warn', { default: 'array' }],
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
];
