import { LatexDictionary } from './public';

export const DEFINITIONS_SYMBOLS: LatexDictionary = [
    // Greek
    { trigger: { symbol: '\\alpha' }, parse: '\u03b1' },
    { trigger: { symbol: '\\beta' }, parse: '\u03b2' },
    { trigger: { symbol: '\\gamma' }, parse: '\u03b3' },
    { trigger: { symbol: '\\delta' }, parse: '\u03b4' },
    { trigger: { symbol: '\\epsilon' }, parse: '\u03f5' },
    { trigger: { symbol: '\\varepsilon' }, parse: '\u03b5' },
    { trigger: { symbol: '\\zeta' }, parse: '\u03b6' },
    { trigger: { symbol: '\\eta' }, parse: '\u03b7' },
    { trigger: { symbol: '\\theta' }, parse: '\u03b8' },
    { trigger: { symbol: '\\vartheta' }, parse: '\u03d1' },
    { trigger: { symbol: '\\iota' }, parse: '\u03b9' },
    { trigger: { symbol: '\\kappa' }, parse: '\u03ba' },
    { trigger: { symbol: '\\varkappa' }, parse: '\u03f0' },
    { trigger: { symbol: '\\lambda' }, parse: '\u03bb' },
    { trigger: { symbol: '\\mu' }, parse: '\u03bc' },
    { trigger: { symbol: '\\nu' }, parse: '\u03bd' },
    { trigger: { symbol: '\\xi' }, parse: '\u03be' },
    { trigger: { symbol: '\\omicron' }, parse: '\u03bf' },
    // { trigger: { symbol: '\\pi' }, parse: '\u03c0' },
    { trigger: { symbol: '\\varpi' }, parse: '\u03d6' },
    { trigger: { symbol: '\\rho' }, parse: '\u03c1' },
    { trigger: { symbol: '\\varrho' }, parse: '\u03f1' },
    { trigger: { symbol: '\\sigma' }, parse: '\u03c3' },
    { trigger: { symbol: '\\varsigma' }, parse: '\u03c2' },
    { trigger: { symbol: '\\tau' }, parse: '\u03c4' },
    { trigger: { symbol: '\\phi' }, parse: '\u03d5' },
    { trigger: { symbol: '\\varphi' }, parse: '\u03c6' },
    { trigger: { symbol: '\\upsilon' }, parse: '\u03c5' },
    { trigger: { symbol: '\\chi' }, parse: '\u03c7' },
    { trigger: { symbol: '\\psi' }, parse: '\u03c8' },
    { trigger: { symbol: '\\omega' }, parse: '\u03c9' },

    { trigger: { symbol: '\\Gamma' }, parse: '\u0393' },
    { trigger: { symbol: '\\Delta' }, parse: '\u0394' },
    { trigger: { symbol: '\\Theta' }, parse: '\u0398' },
    { trigger: { symbol: '\\Lambda' }, parse: '\u039b' },
    { trigger: { symbol: '\\Xi' }, parse: '\u039e' },
    { trigger: { symbol: '\\Pi' }, parse: '\u03a0' },
    { trigger: { symbol: '\\Sigma' }, parse: '\u03a3' },
    { trigger: { symbol: '\\Upsilon' }, parse: '\u03a5' },
    { trigger: { symbol: '\\Phi' }, parse: '\u03a6' },
    { trigger: { symbol: '\\Psi' }, parse: '\u03a8' },
    { trigger: { symbol: '\\Omega' }, parse: '\u03a9' },
    { trigger: { symbol: '\\digamma' }, parse: '\u03dd' },

    // Hebrew
    { trigger: { symbol: '\\aleph' }, parse: '\u2135' },
    { trigger: { symbol: '\\beth' }, parse: '\u2136' },
    { trigger: { symbol: '\\daleth' }, parse: '\u2138' },
    { trigger: { symbol: '\\gimel' }, parse: '\u2137' },

    // Letter-like
    { trigger: { symbol: '\\Finv' }, parse: '\u2132' },
    { trigger: { symbol: '\\Game' }, parse: '\u2141' },
    { trigger: { symbol: '\\wp' }, parse: '\u2118' },
    { trigger: { symbol: '\\eth' }, parse: '\u00f0' },
    { trigger: { symbol: '\\mho' }, parse: '\u2127' },

    // Symbols
    { trigger: { symbol: '\\clubsuit' }, parse: '\u2663' },
    { trigger: { symbol: '\\heartsuit' }, parse: '\u2661' },
    { trigger: { symbol: '\\spadesuit' }, parse: '\u2660' },
    { trigger: { symbol: '\\diamondsuit' }, parse: '\u2662' },
    { trigger: { symbol: '\\sharp' }, parse: '\u266f' },
    { trigger: { symbol: '\\flat' }, parse: '\u266d' },
    { trigger: { symbol: '\\natural' }, parse: '\u266e' },
];
