#! bash

set -e  # exit immediately on error

if [ -z "$GH_PUBLISH_TOKEN"] 
then
    echo "The $GH_PUBLISH_TOKEN env variable is not set, deploy failed."
    echo "Note: the deploy-ci command should only be run from the Travis CI environment"

    exit 1
fi


REPO=$(git config --get remote.origin.url | sed 's/.*:\/\/github.com\///;s/.git$//')
BRANCH=$(git rev-parse --abbrev-ref HEAD)
VERSION=$(git describe --tags)
API_JSON=$(printf '{"tag_name": "%s","target_commitish": "master","name": "%s","body": "Release of version %s","draft": false,"prerelease": false}' $VERSION $VERSION $VERSION)

echo "Create release $VERSION for $BRANCH branch of $REPO"
curl --data "$API_JSON" "https://api.github.com/repos/$REPO/releases?access_token=$GH_PUBLISH_TOKEN"

