#! bash

set -e  # exit immediately on error

if [ "$1" == "minor" ]
then
    npm version minor

elif [ "$1" == "major" ]
then
    npm version major

else
    # if $1 is empty or $1 = 'patch'
    npm version patch
fi

# The "preversion" and "version" scripts are run by the "npm version" command.
# The "npm version" commands above have also created a matching git tag.

# Deploy this tagged release to Github.
# This will trigger a Travis build.
# In turn, the Travis build will publish to npm.
git push origin --tags
